# Site settings
name: 打个酱油
email: charles5533@163.com
author: Charles
url: 个人网站
resume_site: 个人简历网站
github: https://github.com/pythoncharles/
baseurl: "/blogs"
description: Actually, less is more!
meta_description: 王成龙;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

